# Liang's zsh configuration
#
# Author: zhlwish@gmail.com
# Date  : 2012-5-3

export EDITOR=vim

#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

autoload -U compinit
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
setopt APPEND_HISTORY
## for sharing history between zsh processes
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

## never ever beep ever
#setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
#MAILCHECK=0

# autoload -U colors
colors

setopt autocd

# see http://linuxtoy.org/archives/zsh-tip-2.html
user-ret(){
    if [[ $BUFFER = "" ]] ;then
        BUFFER="ls"
        zle end-of-line
        zle accept-line
    elif [[ $BUFFER =~ "^cd\ \.\.\.+$" ]] ;then
        BUFFER=${${BUFFER//\./\.\.\/}/\.\.\//}
        zle end-of-line
        zle accept-line
    else
        zle accept-line
    fi
}

zle -N user-ret
bindkey "\r" user-ret
# end see

bindkey '\eq' push-line-or-edit

alias proxy='nohup ssh -N -2 -D 7070 zhlwish@zhlwish.com -p 22 &'
alias ctags-gen='ctags -R --languages=Ruby --exclude=log --exclude=tmp'
alias ff='find ./ -type f | xargs grep --color --line-number '

# User specific aliases and functions
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
# order by modification time
alias ltr='ll -tr'
# order by file size
alias lsr='ll -Sr'
alias rm='rm -i'
alias cp='cp -i'
alias grep='grep --color=auto'
# find process
alias fp='ps -aux | grep'
alias gb2u8='iconv -f gbk -t utf8 -c'
alias u82gb='iconv -f utf8 -t gbk -c'
alias cls='clear'

# Share current directory as a website
alias hostdir="python -m SimpleHTTPServer"

# For Ubuntu xclip http://blog.csdn.net/pfanaya/article/details/7665853
alias clip=' xclip -selection clipboard '

# The following java_ls and java_use can only be used on Mac OS platforms
# from http://superuser.com/questions/490425/how-do-i-switch-between-java-7-and-java-6-on-os-x-10-8-2
alias java_ls='/usr/libexec/java_home -V 2>&1 -a x86_64  | grep -E "\d.\d.\d[,_]" | cut -d , -f 1 | colrm 1 4 | grep -v Home'

function java_use() {
  export JAVA_HOME=$(/usr/libexec/java_home -v $1)
  export PATH=$JAVA_HOME/bin:$PATH
  java -version
}


# http://hi.baidu.com/hzd2712/item/5c0a4dd2d9a888e0785daaf6
LANG=zh_CN.UTF-8
export LANG
